# Use the official Node.js image as the base image
FROM docker.io/library/node:lts-alpine AS build-env

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the application dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Build the NestJS application
RUN npm run build


#FROM gcr.io/distroless/nodejs24-debian12
FROM docker.io/library/node:lts-alpine

RUN apk add --update \
	curl \
	iproute2-ss \
	&& rm -rf /var/cache/apk/*

COPY --from=build-env /usr/src/app /app
WORKDIR /app 

EXPOSE 3000

CMD ["dist/main.js"]